name: test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  go:
    name: go
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: CI checks
        run: make ci
